# -*- coding: utf-8 -*-
"""Areej.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLfm_kFNFIzPh2_C8Dah8i6IW34M-0SO
"""

a=2
b=1
c=a+b
print("sum=",c)